server: 
  port: 9527
 
spring: 
  application:
    name: microservice-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
    
zuul: 
  prefix: /xmrbi
  ignored-services: microservice-provider-user #忽略原真实服务名
  routes: 
    mydept.serviceId: microservice-provider-user
    mydept.path: /myuser/**
 
info:
  app.name: xmrbi-microservice
  company.name: www.xmrbi.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$